title = "Builder proof-of-concept"

init = [
  "banks",
  "builders",
  "populations"
]
eval = [
  "banks",
  "builders",
  "populations"
]

[recipes]
  [recipes.house]
    label = "House"
    consumable = false
    components = []

[agents]
  [agents.banks]
    [agents.banks.royal_bank]
      module = "bank"
      label = "Royal Bank of Ankh-Morpork"
      initial_deposit = 0

  [agents.builders]
    [agents.builders.builder_1]
      module = "builder"
      label = "Builder 1"
      build_time = 10
      product = "house"
      labour_input = 80
      initial_deposit = 2000
      bank = "royal_bank"
    
    [agents.builders.builder_2]
      module = "builder"
      label = "Builder 2"
      build_time = 10
      product = "house"
      labour_input = 80
      initial_deposit = 2000
      bank = "royal_bank"
    
    [agents.builders.builder_3]
      module = "builder"
      label = "Builder 3"
      build_time = 10
      product = "house"
      labour_input = 80
      initial_deposit = 2000
      bank = "royal_bank"
    
    [agents.builders.builder_4]
      module = "builder"
      label = "Builder 4"
      build_time = 10
      product = "house"
      labour_input = 80
      initial_deposit = 2000
      bank = "royal_bank"
    
    [agents.builders.builder_5]
      module = "builder"
      label = "Builder 5"
      build_time = 10
      product = "house"
      labour_input = 80
      initial_deposit = 2000
      bank = "royal_bank"


  [agents.populations]
    [agents.populations.worker]
      module = "population"
      label = "Worker"
      bank = "royal_bank"
      initial_deposit = 100
      initial_population = 50

      [agents.populations.worker.needs]
        house = {purchase = 1, consume = 1, store = 1, use_loan = true}
    
    [agents.populations.bank_investor]
      module = "bank_investor"
      label = "The Bank Investor"
      bank = "royal_bank"
      initial_investment = 30_000